baseURL = "https://kbe-ja.netlify.com/"
DefaultContentLanguage = "ja"
title = "Kubernetes By Example"
theme = "beautifulhugo"
metaDataFormat = "yaml"
# googleAnalytics = "UA-34425776-2"
contentDir = "content-ja"

[Params]
  subtitle = "kubernetesbyexample.com の日本語訳"
  logo = "img/kbe-logo.png"
  favicon = "img/kbe-logo.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = false

[[menu.main]]
  name = "Try out!"
  url = "diy/"

[[menu.main]]
  name = "Contribute"
  url = "https://github.com/FujiHaruka/kbe-ja"

[[menu.main]]
  name = "Original site"
  url = "http://kubernetesbyexample.com"